# Generated by Django 3.1.5 on 2021-01-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_photo',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
